import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  Alert,
  TouchableOpacity,
  ImageBackground,
  ScrollView,
  ActivityIndicator,
} from 'react-native';
import Icon from 'react-native-vector-icons/Ionicons';
import { deleteTrip } from '../services/api';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

const TripDetailsScreen = ({ route, navigation }) => {
  const { trip, onDelete } = route.params || {};
  const [pdfLoading, setPdfLoading] = React.useState(false);

  if (!trip) {
    return (
      <View style={styles.loadingContainer}>
        <Text style={styles.noTripText}>
          No trip data found. Please go back and select a trip.
        </Text>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.goBackButton}>
          <Text style={styles.goBackButtonText}>Go Back</Text>
        </TouchableOpacity>
      </View>
    );
  }

  const handleDelete = () => {
    Alert.alert(
      'Confirm Delete',
      'Are you sure you want to delete this trip?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: async () => {
            try {
              await deleteTrip(trip._id);
              if (onDelete) onDelete();
              navigation.goBack();
            } catch (err) {
              Alert.alert('Error', 'Failed to delete trip');
              console.error(err);
            }
          },
        },
      ]
    );
  };

  const handleSharePDF = async () => {
    setPdfLoading(true);
    try {
      const html = `
        <html>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <link href="https://fonts.googleapis.com/css?family=Montserrat:700,400&display=swap" rel="stylesheet">
          <style>
            body { font-family: 'Montserrat', Arial, sans-serif; background: #f8fbff; color: #222; margin: 0; padding: 0; }
            .header { background: linear-gradient(90deg, #4A90E2 60%, #FF6F61 100%); color: #fff; padding: 32px 0 18px 0; text-align: center; border-bottom-left-radius: 40px; border-bottom-right-radius: 40px; }
            .header h1 { margin: 0; font-size: 2.2em; font-weight: 700; letter-spacing: 1px; }
            .section { margin: 32px 24px 0 24px; }
            .section-title { color: #4A90E2; font-size: 1.25em; font-weight: 900; margin-bottom: 10px; display: flex; align-items: center; letter-spacing: 0.5px; }
            .icon { font-size: 1.1em; margin-right: 8px; }
            .desc { font-size: 1.08em; margin-bottom: 14px; color: #444; }
            .dates { color: #FF6F61; font-weight: 700; margin-bottom: 20px; font-size: 1.08em; }
            .itinerary-table { width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 1.05em; }
            .itinerary-table th, .itinerary-table td { border: 1px solid #e3e9f7; padding: 12px 8px; text-align: left; }
            .itinerary-table th { background: #e3e9f7; color: #4A90E2; font-weight: 900; font-size: 1.08em; }
            .itinerary-table tr:nth-child(even) td { background: #f3f6fa; }
            .itinerary-table tr:nth-child(odd) td { background: #fff; }
            .notes { color: #FF6F61; font-style: italic; font-size: 1.04em; font-weight: 600; letter-spacing: 0.2px; }
            .footer { margin: 40px 0 0 0; text-align: center; color: #aaa; font-size: 0.98em; letter-spacing: 0.5px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>🌍 ${trip.title}</h1>
          </div>
          <div class="section">
            <div class="section-title"><span class="icon">📝</span>Description</div>
            <div class="desc">${trip.description || 'No description provided'}</div>
            <div class="section-title"><span class="icon">📅</span>Dates</div>
            <div class="dates">${new Date(trip.startDate).toDateString()} &rarr; ${new Date(trip.endDate).toDateString()}</div>
          </div>
          <div class="section">
            <div class="section-title"><span class="icon">🗺️</span>Itinerary</div>
            <table class="itinerary-table">
              <tr><th>Day</th><th>Activities</th><th>Notes</th></tr>
              ${(trip.itinerary || []).map(day => `
                <tr>
                  <td><b>${day.day}</b></td>
                  <td>${day.activities.join(', ') || 'No activities'}</td>
                  <td class="notes">${day.notes || ''}</td>
                </tr>
              `).join('')}
            </table>
          </div>
          <div class="footer">Generated by Travel Planner App</div>
        </body>
        </html>
      `;
      const { uri } = await Print.printToFileAsync({ html });
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: 'Share Trip PDF',
      });
    } catch (err) {
      Alert.alert('Error', 'Could not generate or share PDF.');
      console.error(err);
    }
    setPdfLoading(false);
  };

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
          <Icon name="arrow-back" size={24} color="#1A3C6D" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Trip Details</Text>
      </View>

      <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">

        {/* Trip Card with Image, Title, Description & Dates */}
        <ImageBackground
          source={{
            uri: trip.image?.trim() || 'https://source.unsplash.com/800x600/?travel',
          }}
          style={styles.tripImage}
          imageStyle={{ borderRadius: 12 }}
        >
          <View style={styles.imageOverlay}>
            <Text style={styles.tripTitle}>{trip.title}</Text>
            {/* Description inside card */}
            <Text style={styles.tripDescription} numberOfLines={2}>
              {trip.description || 'No description provided'}
            </Text>
            {/* Dates inside card */}
            <Text style={styles.tripDates}>
              {new Date(trip.startDate).toDateString()} → {new Date(trip.endDate).toDateString()}
            </Text>
          </View>
        </ImageBackground>

        {/* Share and Edit Buttons */}
        <TouchableOpacity
          style={[
            styles.editButton,
            {
              backgroundColor: '#FF6F61',
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'center',
              marginBottom: 10,
            },
          ]}
          onPress={handleSharePDF}
          disabled={pdfLoading}
        >
          <Icon name="document-outline" size={20} color="#fff" style={styles.buttonIcon} />
          <Text style={styles.editButtonText}>Share as PDF</Text>
          {pdfLoading && <ActivityIndicator size="small" color="#fff" style={{ marginLeft: 8 }} />}
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.editButton}
          onPress={() =>
            navigation.navigate('CreateTrip', {
              isEdit: true,
              trip,
              onGoBack: onDelete,
            })
          }
        >
          <Icon name="create-outline" size={20} color="#fff" style={styles.buttonIcon} />
          <Text style={styles.editButtonText}>Edit Trip</Text>
        </TouchableOpacity>

        {/* Itinerary Section */}
        <View style={styles.detailsCard}>

          <Text style={styles.sectionTitle}>Itinerary 📅</Text>

          <ScrollView style={styles.itineraryScroll} nestedScrollEnabled>
            {trip.itinerary?.length > 0 ? (
              trip.itinerary.map((day, index) => (
                <View key={index} style={styles.itineraryCard}>
                  <Text style={styles.itineraryDay}>Day {day.day}</Text>
                  <Text style={styles.itineraryActivities}>
                    {day.activities.join(', ') || 'No activities'}
                  </Text>
                  {day.notes ? <Text style={styles.itineraryNotes}>📝 {day.notes}</Text> : null}
                </View>
              ))
            ) : (
              <Text style={styles.placeholderText}>No itinerary added yet.</Text>
            )}
          </ScrollView>

          <TouchableOpacity
            style={styles.editButton}
            onPress={() =>
              navigation.navigate('EditItinerary', {
                trip,
                onSave: onDelete,
              })
            }
          >
            <Icon name="calendar-outline" size={20} color="#fff" />
            <Text style={styles.editButtonText}>
              {trip.itinerary?.length > 0 ? 'Edit Itinerary' : 'Add Itinerary'}
            </Text>
          </TouchableOpacity>
        </View>

        <TouchableOpacity
          style={styles.galleryButton}
          onPress={() => navigation.navigate('TripGallery', { tripId: trip._id })}
        >
          <Icon name="images-outline" size={20} color="#fff" style={styles.buttonIcon} />
          <Text style={styles.galleryButtonText}>View Photos</Text>
        </TouchableOpacity>

        <TouchableOpacity style={styles.deleteButton} onPress={handleDelete}>
          <Icon name="trash-outline" size={20} color="#fff" style={styles.buttonIcon} />
          <Text style={styles.deleteButtonText}>Delete Trip</Text>
        </TouchableOpacity>
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#E6F0FA' },
  loadingContainer: {
    flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 30,
  },
  noTripText: {
    fontSize: 18, color: '#666', textAlign: 'center', marginBottom: 20,
  },
  goBackButton: {
    backgroundColor: '#4A90E2', paddingHorizontal: 24, paddingVertical: 12, borderRadius: 25,
  },
  goBackButtonText: {
    color: '#fff', fontSize: 16, fontWeight: '600',
  },
  header: {
    flexDirection: 'row', alignItems: 'center',
    paddingHorizontal: 20, paddingTop: 60, paddingBottom: 20,
  },
  backButton: { padding: 10 },
  headerTitle: {
    fontSize: 26, fontWeight: '700', color: '#1A3C6D',
    flex: 1, textAlign: 'center',
  },
  content: { paddingHorizontal: 20, paddingBottom: 40 },
  tripImage: {
    height: 200, justifyContent: 'flex-end', marginBottom: 16,
  },
  imageOverlay: {
    flex: 1, backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 12, padding: 16, justifyContent: 'flex-end',
  },
  tripTitle: { fontSize: 24, fontWeight: '700', color: '#fff' },
  tripDescription: {
    fontSize: 14,
    color: '#ffffff',
    marginTop: 4,
    fontStyle: 'italic',
    maxHeight: 40,
  },
  tripDates: {
    fontSize: 13,
    color: '#ffffffff',
    marginTop: 2,
    fontWeight: '600',
  },
  detailsCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    marginBottom: 16,
    // Removed maxHeight to allow full height for itinerary + button
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 10,
    color: '#1A3C6D',
  },
  itineraryScroll: {
    maxHeight: 140,
    marginBottom: 10,
  },
  itineraryCard: {
    backgroundColor: '#f8f8f8', borderRadius: 10, padding: 10, marginBottom: 6,
  },
  itineraryDay: { fontWeight: 'bold', fontSize: 16, color: '#333' },
  itineraryActivities: { color: '#555', marginTop: 4 },
  itineraryNotes: { color: '#777', marginTop: 4, fontStyle: 'italic' },
  placeholderText: { fontSize: 16, color: '#888', fontStyle: 'italic', marginBottom: 10 },
  editButton: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    backgroundColor: '#4A90E2', paddingVertical: 14,
    borderRadius: 12, marginBottom: 10,
  },
  editButtonText: { fontSize: 18, fontWeight: '600', color: '#fff', marginLeft: 8 },
  deleteButton: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    backgroundColor: '#D32F2F', paddingVertical: 16,
    borderRadius: 12, elevation: 3,
    shadowColor: '#000', shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2, shadowRadius: 3,
    marginBottom: 30,
  },
  deleteButtonText: { fontSize: 18, fontWeight: '600', color: '#fff', marginLeft: 8 },
  buttonIcon: { marginRight: 8 },
  galleryButton: {
    flexDirection: 'row', backgroundColor: '#00AEEF',
    paddingVertical: 16, borderRadius: 12,
    justifyContent: 'center', alignItems: 'center',
    marginBottom: 16,
  },
  galleryButtonText: { color: '#fff', fontWeight: '600', fontSize: 16 },
});

export default TripDetailsScreen;
